site_name: Aspy Dependency Injection
repo_url: https://github.com/AndreuCodina/aspy-dependency-injection
repo_name: AndreuCodina/aspy-dependency-injection
docs_dir: pages
watch:
  - code
  - ../src
strict: true
validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    anchors: warn
    absolute_links: warn
    unrecognized_links: warn
theme:
  name: material
  features:
    - navigation.expand
    - navigation.path
    - toc.follow
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            group_by_category: true
            show_category_heading: false
            show_signature: true
            show_signature_annotations: true
            show_if_no_docstring: false
            separate_signature: true
            show_overloads: true
            overloads_only: true
            show_bases: true
            inherited_members: true
            docstring_style: sphinx
            show_source: false
nav:
  - Introduction: index.md
  - Getting started:
      - Installation: getting-started/installation.md
      - Quickstart: getting-started/quickstart.md
      - FastAPI integration: getting-started/fastapi-integration.md
  - Core concepts:
      - Service lifetimes: core-concepts/lifetimes.md
      - Factories: core-concepts/factories.md
      - Async-first design: core-concepts/async-first-design.md
      - Pluggable architecture: core-concepts/pluggable-architecture.md
  - Testing: testing.md
  - Advanced features:
      - Interfaces & abstract classes: advanced-features/interfaces-and-abstract-classes.md
      - Keyed services: advanced-features/keyed-services.md
      - Auto-activated services: advanced-features/auto-activated-services.md
  - API reference:
      - ServiceCollection: api-reference/service-collection.md
      - ServiceProvider: api-reference/service-provider.md
      - ServiceScope: api-reference/service-scope.md
      - KeyedService: api-reference/keyed-service.md
      - BaseServiceProvider: api-reference/base-service-provider.md
      - ServiceScopeFactory: api-reference/service-scope-factory.md
      - ServiceProviderIsService: api-reference/service-provider-is-service.md
      - ServiceProviderIsKeyedService: api-reference/service-provider-is-keyed-service.md
      - Exceptions: api-reference/exceptions.md
  - Other:
      - Changelogs: other/changelogs.md
