name: Publish documentation

on:
  workflow_call:
  workflow_dispatch:

env:
  UV_NO_SYNC: 1

jobs:
  publish-documentation:
    runs-on: ubuntu-24.04
    permissions:
      contents: write # Allow mkdocs to push to gh-pages branch
    env:
      UV_NO_SYNC: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
        with:
          version-file: pyproject.toml
          resolution-strategy: lowest

      - name: Install Python packages
        run: uv sync --locked
        shell: bash

      - name: Publish documentation
        run: uv run -- mkdocs gh-deploy --config-file docs/mkdocs.yml --remote-branch gh-pages --clean --force --strict
