name: Main

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish-coverage:
    runs-on: ubuntu-24.04
    permissions:
      contents: write # Allow mkdocs to push to gh-pages branch
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
        with:
          version-file: pyproject.toml
          resolution-strategy: lowest

      - name: Install Python packages
        run: uv sync --locked
        shell: bash

      - name: Test
        run: uv run --frozen -- pytest --cov=aspy_dependency_injection --cov-branch --cov-report=xml tests
        shell: bash

      - name: Publish coverage
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/coverage.xml

      - name: Publish documentation
        run: uv run --frozen -- mkdocs gh-deploy --config-file docs/mkdocs.yml --remote-branch gh-pages --clean --force --strict
