name: Main

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    name: Test
    uses: ./.github/workflows/_test.yaml
    permissions:
      contents: write

  publish-documentation:
    needs: test
    runs-on: ubuntu-24.04
    permissions:
      contents: write # Allow mkdocs to push to gh-pages branch
    env:
      UV_NO_SYNC: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@803947b9bd8e9f986429fa0c5a41c367cd732b41 # v7.2.1
        with:
          version-file: pyproject.toml
          resolution-strategy: lowest

      - name: Install Python packages
        run: uv sync --locked
        shell: bash

      - name: Publish documentation
        run: uv run -- mkdocs gh-deploy --config-file docs/mkdocs.yml --remote-branch gh-pages --clean --force --strict
