name: Pull request

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  continuous-integration:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.14"]
        resolution-strategy: ["lowest-direct", "highest"]
    env:
      CI: true # Enable pytest CI mode
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7.1.6
        with:
          version-file: pyproject.toml
          resolution-strategy: lowest
          python-version: ${{ matrix.python-version }}

      - name: Install Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python packages
        run: uv sync --resolution ${{ matrix.resolution-strategy }}
        shell: bash

      - name: Check code
        run: make check-code-pyright
        shell: bash

      - name: Type-check with ty
        run: uv run --frozen -- ty check
        shell: bash
        continue-on-error: true

      - name: Tests
        run: uv run --frozen -- pytest --cov=aspy_dependency_injection --cov-branch tests
        shell: bash
