name: Pull request

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  check-code:
    name: Check code
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-24.04
    env:
      UV_NO_SYNC: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@803947b9bd8e9f986429fa0c5a41c367cd732b41 # v7.2.1
        with:
          version-file: pyproject.toml
          resolution-strategy: lowest

      - name: Install Python packages
        run: uv sync --locked --all-extras
        shell: bash

      - name: Check code
        run: make check-code
        shell: bash

  test:
    name: Test
    uses: ./.github/workflows/_test.yaml
    needs: check-code
    permissions:
      contents: write
